# ----------------------------------------------------------------------------#
#                                                                             #
#                              Battleship config                              #
#                                                                             #
# ----------------------------------------------------------------------------#


# number of ships in the game (only 1 or 2)
#
# size: 5 blocks
aircraftCarrier: 1
# size: 4 blocks
battleship: 1
# size: 3 blocks
cruiser: 2
# size: 2 blocks
destroyer: 1

gameRules:
  # if this is true players can shoot again after a hit and the grids will change after every miss
  #   if it is false the grid will change after every shot regardless of hit/miss
  fireAgainAfterHit: true
  # false: the player whose fire timer ran out will loose the game
  # true: If a fire timer runs out it's the other players turn
  switchAttackerAfterFireTimerRanOut: false

# some stuff you can do when a game ends.
onGameEnd:
  # You can dispatch commands. Use %winner% for the playername of the winner and %looser% for the looser
  dispatchCommands:
    enabled: false
    commands:
    - "give %winner% diamond 1"
    - "tell %winner% congrats!"
    - "tell %looser% next time you'll beat him!"
  # You can broadcast. Use %winner% for the playername of the winner and %looser% for the looser
  broadcast:
    enabled: false
    messages:
    - "%winner% won against %looser% in a game of Battleship!"
    - "Do &2/bs %winner% &rto try against %winner% yourself ;)"


# requires vault and an economy plugin
economy:
  enabled: false
  # both players pay
  cost: 0
  # winner gets
  reward: 0

# use "Material:data" or "ID:data"
# Some materials can not be displayed in an inventory, just test everything after changing
# You are advised to use different materials. At least on the same grid
#   otherwise the game could break
materials:
  yourGrid:
    ship:
      material: "Iron_block"
      name: "&7Ship"
    lockedShip:
      material: "7"
      name: "&8Locked ship"
    miss:
      material: "160:3"
      name: "&2Yeah! A miss!"
    hit:
      material: "35:14"
      name: "&4Damn! A hit..."
    water:
      material: "160:11"
      name: "&1Water"
  othersGrid:
    cover:
      material: "WOOL:7"
      name: "&6Cover"
    miss:
      material: "160:11"
      name: "&4That did not hit..."
    hit:
      material: "Iron_block"
      name: "&2Booom! Gotcha"

    
# Customise the timers used in the game (all times in seconds)
timers:
  # timer used during the ship-set part of the game
  shipSetTimer:
    countdown: 30
  # timer used during the main part of the game
  fireTimer:
    countdown: 10
  # timer used when attacker and defender change
  changingGrids:
    countdown: 3
  # timer used for the invitations
  invitationTimer:
    validFor: 15