# ----------------------------------------------------------------------------#
#                                                                             #
#                              Connect4 config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "57"
    # display name of the button
    displayName: "&3Connect4"
    # lore of the button
    lore:
    - ""
    - "&1Get 4 in a row"
  gameButtons:
    easy:
      materialData: "WOOL:13"
      displayName: "&aTest1"
      lore:
      - ""
      - "&1Cost: &45"
      - "&1Reward: &a7"
      - "&1Tokens: &a3"
      slot: 11
      cost: 5
      reward: 7
      tokens: 3
    saveStats:
      materialData: "diamond_block"
      displayName: "&c&lCompetition"
      lore:
      - ""
      - "&cClimb up the &ltop list"
      - "&aGood luck!"
      - ""
      - "&1Cost: &450"
      - "&1Reward: &a75"
      - "&1Tokens: &a3"
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
      tokens: 3
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "diamond_block"
      displayName: "&cTop list"
      lore:
      - ""
      - "&cCompetition &1top list"
      slot: 33
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the time in 'mm:ss'
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Score:&1 %score%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false


chips:
  enzy:
    materialData: "340"
    displayName: "&3Encyclopedia"
    lore:
    - ""
    - "&cHeavy book"
  sparks:
    materialData: "377"
    displayName: "&3Sparks"
