# ----------------------------------------------------------------------------#
#                                                                             #
#                             Minesweeper config                              #
#                                                                             #
# ----------------------------------------------------------------------------#
# number of mines in the game (only integer from 1 to 30)
mines: 8

rules:
  # when you reveal an empty slot automatic revealing will uncover all attached empty slots until the first slot
  #   is not empty
  # change this to true if you DON'T want this option
  turnOffAutomaticRevealing: false


# requires vault and an economy plugin
economy:
  enabled: false
  cost: 0
  reward: 0


# you can use the section below to run commands if a player won a game
#   %player% will be replaced by the players name
wonCommands:
  enabled: false
  # commands to dispatch after a player won a game
  commands:
  - "tell %player% [Minesweeper] You won a diamond"
  - "give %player% diamond 1"


# use "Material:data" or "ID:data"
materials:
  cover: "160:7"
  flag: "SIGN"
  mine: "TNT"
  warning: "WOOL:1"

displaynames:
  cover: "Cover"
  warning: "Warning"
  mine: "Boooom!"
  flag: "Flag"