# ----------------------------------------------------------------------------#
#                                                                             #
#                              GemCrush config                                #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwriten on every server restart! This means you will have to use the other files
#     to customize the messages, but since i am adding messages regulary in updates 
#   You should use the default file if you just want to have the up to date english default messages
langFile: 'default.yml'

game:
  # number of moves in a default game
  moves: 20
  # time in ticks (20 ticks = 1 second) between two gem movements
  #   this is time each gem needs to fall down one row
  ticksBetweenMovement: 3
  # time in ticks (20 ticks = 1 second) between switching two gems and destroying the matched ones
  ticksBetweenSwitchAndDestroy: 7
  # number of different gems in a normal game
  #   This number HAS TO BE equal or smaller then the number of gems defined in the section normalGems below
  #   8 or 7 are good numbers. 7 is easier and the game has to shuffle less but 8 is a bit more challenging
  numberOfNormalGems: 8



# requires vault and an economy plugin
#   to pay out the rewards from section 'onGameEnd' economy.enabled AND onGameEnd.pay have to be true
#   if economy.enabled is true players will pay the cost when starting a game
economy:
  enabled: false
  cost: 10


onGameEnd:
  pay: true
  sendMessages: false
  sendBroadcasts: false
  dispatchCommands: false
  scoreIntervals:
    # all keys have to be integers otherwise they will be ignored and a warning will be printed in the console

    # money is only paid if economy is enabled

    # You can add as many intervalls as you want to. The order of the intervalls doesn't matter
    #   the given reward/messages/commands/broadcasts will always be used if the game is finished with a score between the key and the
    #   next higher key. For the highest key the intervall goes to infinity
    # You can add a money-reward with money: x; messages to send to the player with messages: (as list);
    #   commands: (as a list); broadcast: (as list)

    # use %player% for the players name and %score% for the score

    # FYI: there is a message in the language file that will always be send after a game
    #   only add aditional messages in this section
    0:
      money: 0
      messages:
      - ' &2you can do better than that...'
      - ' &4try again &1;)'
    100:
      money: 100
    200:
      money: 200
    300:
      money: 300
    400:
      money: 400
      commands:
      - 'tell %player% congrats ;)'
      - 'tell %player% you scored %score%!'
    500:
      money: 500
      messages:
      - ' &2%score% wow! &1Thats not bad ^^'
      # - ' &2You won a diamond'
      commands:
      - 'tell %player% you scored %score%!'
      # - 'give %player% diamond 1'
      broadcast:
      - '%player% finished a game of &2GemCrush&r with &2%score% &rpoints!'
      - 'Do &2/gc &rto prove that you are better ;)'



# use 'Material:data' or 'ID:data'
# Some materials can not be displayed in an inventory, just test everything after changing
#   there are also some materials that don't work for this plugin (for example: snowball)
#   i'll try fixing that
# You are advised to use different materials.
# The displaynames have to be different for the game to work!
# Add as many gems as you want the game will choose random ones for every round
normalGems:
  gem1:
    material: 'Diamond'
    displayName: "Diamond"
    # optional custom number of points per destroyed gem of this type
    #   the default is 10 and is used if this option is not set
    pointsOnBreak: 10
    # optional probability for this gem to be used
    #   default is 1 and is used if this option is not set
    # This is NOT the probability for the gem to be used to fill an empty slot in the game
    #   this probability is used when the game decides which normal gems to use for the game
    probability: 2
  gem2:
    material: 'EMERALD'
    displayName: 'Emerald'
    pointsOnBreak: 10
    probability: 1
  gem3:
    material: 'BLAZE_POWDER'
    displayName: 'Sparks'
    pointsOnBreak: 10
    probability: 1
  gem4:
    material: 'clay_ball'
    displayName: 'Pearl'
  gem5:
    material: 'gold_block'
    displayName: 'Gold'
  gem6:
    material: 'iron_block'
    displayName: 'Iron'
  gem7:
    material: 'bone'
    displayName: 'Fossil'
  gem8:
    material: 'apple'
    displayName: 'Apple'
  gem9:
    material: 'anvil'
    displayName: 'Anvil'
  gem10:
    material: 'chest'
    displayName: 'Treasure'
  gem11:
    material: 'double_plant'
    displayName: 'Amber'

